//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCode.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbStudentEntities : DbContext
    {
        public dbStudentEntities()
            : base("name=dbStudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminMaster> adminMasters { get; set; }
        public virtual DbSet<assignmentMaster> assignmentMasters { get; set; }
        public virtual DbSet<chatmaster> chatmasters { get; set; }
        public virtual DbSet<exammaster> exammasters { get; set; }
        public virtual DbSet<facultymaster> facultymasters { get; set; }
        public virtual DbSet<feedbackmaster> feedbackmasters { get; set; }
        public virtual DbSet<studentMaster> studentMasters { get; set; }
    }
}
