//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCode.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class exammaster
    {
        [Key]
        public int eid { get; set; }
        [Required]
        public string ename { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> edate { get; set; }
        [Required]
        public string subjectname { get; set; }
        [Required]
        public string egroup { get; set; }
    }
}
