//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCode.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class studentMaster
    {
        public int sid { get; set; }
        [Required]
        [MinLength(3)]
        [MaxLength(20)]
        public string sname { get; set; }
        [Required]
        [MinLength(3)]
        [MaxLength(20)]
        public string fname { get; set; }
        [Required]
        [MinLength(3)]
        [MaxLength(20)]
        public string lname { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string emailid { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public string gender { get; set; }
        public string image { get; set; }
        [Required]
        public string college { get; set; }
        [Required]
        public string country { get; set; }
        [Required]
        public string state { get; set; }
        [Required]
        public string city { get; set; }
    }
}
